Repository rebase-network/2022Q4-hackathon, pull requests merged in 2022-12, with the labels that each got.

#35 PR35-MuseTime
  projects/01-RebaseNFT/.keep
  projects/01-RebaseNFT/README.md
  projects/01-RebaseNFT/docs/.keep
  projects/01-RebaseNFT/docs/rebasenft.md
  projects/35-MuseTime/README.md
Labels: socialfi

#34 PR34-Choko Wallet
  projects/34-ChokoWallet/.keep
  projects/34-ChokoWallet/README.md
Labels: wallet

#33 PR33-add social layer
  projects/33-sociallayer/README.md
Labels: dao, sbt, socialfi

#29 PR29-Canary3
  projects/.DS_Store
  projects/29-canary3/.gitignore
  projects/29-canary3/README.md
  projects/29-canary3/docs/canary3.md
Labels: trading

#26 PR26 add team info of UniLender
  projects/01-RebaseNFT/PR26-UniLender/README.md
Labels: Defi

#25 PR25-Footrace
  projects/25-Footrace/README.md
  projects/25-Footrace/alert/Dockerfile
  projects/25-Footrace/alert/Makefile
  projects/25-Footrace/alert/config.yaml
  projects/25-Footrace/alert/requirements.txt
  projects/25-Footrace/alert/rules/twitterscan_trending_topics.yaml
  projects/25-Footrace/client/.eslintrc.json
  projects/25-Footrace/client/.gitignore
  projects/25-Footrace/client/README.md
  projects/25-Footrace/client/next.config.js
  projects/25-Footrace/client/package.json
  projects/25-Footrace/client/pages/_app.tsx
  projects/25-Footrace/client/pages/_document.tsx
  projects/25-Footrace/client/pages/api/cex.ts
  projects/25-Footrace/client/pages/api/topic.ts
  projects/25-Footrace/client/pages/index.tsx
  projects/25-Footrace/client/styles/globals.css
  projects/25-Footrace/client/tsconfig.json
  projects/25-Footrace/client/yarn.lock
  projects/25-Footrace/connector/Dockerfile
  projects/25-Footrace/connector/Makefile
  projects/25-Footrace/connector/config/logstash.yml
  projects/25-Footrace/connector/config/pipelines.yml
  projects/25-Footrace/connector/src/twitterscan_trending_topics.conf
  projects/25-Footrace/docs/demo.md
Labels: data analysis

#24 PR 24 GameOn
  projects/24-GameOn/.keep
  projects/24-GameOn/README.md
  projects/24-GameOn/docs/.keep
Labels: game, wallet, tool

#22 PR22-Middleware.web3
  projects/22-Middleware.web3/README.md
  projects/22-Middleware.web3/docs/ERC721Cross.pdf
  projects/22-Middleware.web3/docs/ERC721Cross.pptx
Labels: tool

#18 PR18-FairVote
  projects/18-FairVote/README.md
Labels: dao, tool

#15 PR15-Donate3
  .gitignore
  projects/15-Donate3/README.md
  projects/15-Donate3/commits.png
  projects/15-Donate3/docs/donate3.md
Labels: dao, tool

#13 PR13-Git3
  projects/13-Git3/README.md
  projects/13-Git3/docs/.keep
  projects/13-Git3/docs/clone_repo.png
  projects/13-Git3/docs/create_repo.png
  projects/13-Git3/docs/git3.md
  projects/13-Git3/docs/git3_help.png
  projects/13-Git3/docs/git3_new.png
  projects/13-Git3/docs/init_repo.png
  projects/13-Git3/docs/push_repo.png
Labels: tool

#10 PR10-DAOLink
  projects/DAOLink/README.md
Labels: dao

#9 PR09-DAO-Plugins-Based-On-Github
  projects/09-DoG/README.md
  projects/09-DoG/docs/.gitkeep
  projects/09-DoG/docs/Deck of DoG.pdf
Labels: dao, tool

#4 PR04-DAOTaskPay
  04-DAOTaskPay/README.md
Labels: dao, tool

#36 PR36-Soul Faucet
  projects/SoulFaucet/README.md
Labels: dao, sbt

#6 PR06-RoboHorse
  projects/06-RoboHorse/README.md
  projects/06-RoboHorse/docs/RoboHorse项目介绍.docx
Labels: trading
